#coding=utf-8
#Team Dicts
Teamabbrs = {}
Teamfull = {}
Teamabbrs['生命科学学院'] = ['BIO']
Teamabbrs['微纳电子系'] = ['IME']
Teamabbrs['数学科学系'] = ['MAT']
Teamabbrs['软件学院'] = ['SS']
Teamabbrs['地球系统科学系'] = ['ESS']
Teamabbrs['土木建管系'] = ['CIE']
Teamabbrs['美术学院'] = ['AAD']
Teamabbrs['法学院'] = ['LAW']
Teamabbrs['新闻与传播学院'] = ['SJC']
Teamabbrs['水利水电工程系'] = ['HE']
Teamabbrs['化学系'] = ['CHE']
Teamabbrs['新雅书院'] = ['XYC']
Teamabbrs['电机系'] = ['EEA']
Teamabbrs['医学院'] = ['MED']
Teamabbrs['公共管理学院'] = ['PPM']
Teamabbrs['社会科学学院'] = ['SSS']
Teamabbrs['环境学院'] = ['ENV']
Teamabbrs['核研院'] = ['NET']
Teamabbrs['五道口金融学院'] = ['PBC']
Teamabbrs['热能工程系'] = ['TE']
Teamabbrs['能动系'] = ['TE']
Teamabbrs['交叉信息院'] = ['IIS']
Teamabbrs['物理系'] = ['PHY']
Teamabbrs['工程物理系'] = ['EP']
Teamabbrs['航天航空学院'] = ['AE']
Teamabbrs['电子工程系'] = ['EE']
Teamabbrs['机械工程系'] = ['ME']
Teamabbrs['经济管理学院'] = ['SEM']
Teamabbrs['工业工程系'] = ['IE']
Teamabbrs['建筑学院'] = ['ARC']
Teamabbrs['人文学院'] = ['SH']
Teamabbrs['苏世民书院'] = ['SC']
Teamabbrs['化学工程系'] = ['CE']
Teamabbrs['精密仪器系'] = ['DPI']
Teamabbrs['计算机系'] = ['CS']
Teamabbrs['汽车工程系'] = ['DAE']
Teamabbrs['自动化系'] = ['DA']
Teamabbrs['材料学院'] = ['MSE']

Teamfull['生命'] = ['生命科学学院', '生命科学学院']
Teamfull['生科'] = ['生命科学学院', '生命科学学院']
Teamfull['生院'] = ['生命科学学院', '生命科学学院']
Teamfull['生命学院'] = ['生命科学学院', '生命科学学院']
Teamfull['生命科学学院'] = ['生命科学学院', '生命科学学院']
Teamfull['微电'] = ['微纳电子系', '微纳电子系']
Teamfull['微电子'] = ['微纳电子系', '微纳电子系']
Teamfull['微纳电子系'] = ['微纳电子系', '微纳电子系']
Teamfull['数学'] = ['数学科学系', '数学科学系']
Teamfull['数学系'] = ['数学科学系', '数学科学系']
Teamfull['数学科学系'] = ['数学科学系', '数学科学系']
Teamfull['软件'] = ['软件学院', '软件学院']
Teamfull['软院'] = ['软件学院', '软件学院']
Teamfull['软件学院'] = ['软件学院', '软件学院']
Teamfull['地学'] = ['地球系统科学系', '地球系统科学系']
Teamfull['地学系'] = ['地球系统科学系', '地球系统科学系']
Teamfull['地球系统科学系'] = ['地球系统科学系', '地球系统科学系']
Teamfull['土木'] = ['土木建管系', '土木建管系']
Teamfull['土木系'] = ['土木建管系', '土木建管系']
Teamfull['土木建管系'] = ['土木建管系', '土木建管系']
Teamfull['美术'] = ['美术学院', '美术学院']
Teamfull['美院'] = ['美术学院', '美术学院']
Teamfull['美术学院'] = ['美术学院', '美术学院']
Teamfull['法学'] = ['法学院', '法学院']
Teamfull['法学院'] = ['法学院', '法学院']
Teamfull['新闻'] = ['新闻与传播学院', '新闻与传播学院']
Teamfull['新闻学院'] = ['新闻与传播学院', '新闻与传播学院']
Teamfull['新闻与传播学院'] = ['新闻与传播学院', '新闻与传播学院']
Teamfull['水利'] = ['水利水电工程系', '水利水电工程系']
Teamfull['水利系'] = ['水利水电工程系', '水利水电工程系']
Teamfull['水利水电工程系'] = ['水利水电工程系', '水利水电工程系']
Teamfull['化学'] = ['化学系', '化学系']
Teamfull['化学系'] = ['化学系', '化学系']
Teamfull['新雅'] = ['新雅书院', '新雅书院']
Teamfull['新雅书院'] = ['新雅书院', '新雅书院']
Teamfull['电机'] = ['电机系', '电机工程与应用电子技术系']
Teamfull['电机系'] = ['电机系', '电机工程与应用电子技术系']
Teamfull['电机工程与应用电子技术系'] = ['电机系', '电机工程与应用电子技术系']
Teamfull['医学'] = ['医学院', '医学院']
Teamfull['医学院'] = ['医学院', '医学院']
Teamfull['公管'] = ['公共管理学院', '公共管理学院']
Teamfull['公管学院'] = ['公共管理学院', '公共管理学院']
Teamfull['公共管理学院'] = ['公共管理学院', '公共管理学院']
Teamfull['社科'] = ['社会科学学院', '社会科学学院']
Teamfull['社科学院'] = ['社会科学学院', '社会科学学院']
Teamfull['社会科学学院'] = ['社会科学学院', '社会科学学院']
Teamfull['环境'] = ['环境学院', '环境学院']
Teamfull['环境学院'] = ['环境学院', '环境学院']
Teamfull['核研院'] = ['核研院', '核能与新能源技术研究院']
Teamfull['核研'] = ['核研院', '核能与新能源技术研究院']
Teamfull['核能与新能源技术研究院'] = ['核研院', '核能与新能源技术研究院']
Teamfull['五金'] = ['五道口金融学院', '五道口金融学院']
Teamfull['五道口金融学院'] = ['五道口金融学院', '五道口金融学院']
Teamfull['热能'] = ['热能工程系', '热能工程系']
Teamfull['热能系'] = ['热能工程系', '热能工程系']
Teamfull['热能工程系'] = ['热能工程系', '热能工程系']
Teamfull['能动'] = ['能动系', '能源与动力工程系']
Teamfull['能动系'] = ['能动系', '能源与动力工程系']
Teamfull['能源与动力工程系'] = ['能动系', '能源与动力工程系']
Teamfull['交叉'] = ['交叉信息院', '交叉信息研究院']
Teamfull['叉院'] = ['交叉信息院', '交叉信息研究院']
Teamfull['交叉信息院'] = ['交叉信息院','交叉信息研究院']
Teamfull['交叉信息研究院'] = ['交叉信息院','交叉信息研究院']
Teamfull['物理'] = ['物理系', '物理系']
Teamfull['物理系'] = ['物理系', '物理系']
Teamfull['工物'] = ['工程物理系', '工程物理系']
Teamfull['工物系'] = ['工程物理系', '工程物理系']
Teamfull['工程物理系'] = ['工程物理系', '工程物理系']
Teamfull['航天航空学院'] = ['航天航空学院', '航天航空学院']
Teamfull['航院'] = ['航天航空学院', '航天航空学院']
Teamfull['电子'] = ['电子工程系', '电子工程系']
Teamfull['电子系'] = ['电子工程系', '电子工程系']
Teamfull['电子工程系'] = ['电子工程系', '电子工程系']
Teamfull['机械'] = ['机械工程系', '机械工程系']
Teamfull['机械系'] = ['机械工程系', '机械工程系']
Teamfull['机械工程系'] = ['机械工程系', '机械工程系']
Teamfull['经管'] = ['经济管理学院', '经济管理学院']
Teamfull['经管学院'] = ['经济管理学院', '经济管理学院']
Teamfull['经济管理学院'] = ['经济管理学院', '经济管理学院']
Teamfull['工工'] = ['工业工程系', '工业工程系']
Teamfull['工业'] = ['工业工程系', '工业工程系']
Teamfull['工业系'] = ['工业工程系', '工业工程系']
Teamfull['工业工程系'] = ['工业工程系', '工业工程系']
Teamfull['建筑'] = ['建筑学院', '建筑学院']
Teamfull['建筑学院'] = ['建筑学院', '建筑学院']
Teamfull['人文'] = ['人文学院', '人文学院']
Teamfull['人文学院'] = ['人文学院', '人文学院']
Teamfull['苏世民'] = ['苏世民书院', '苏世民书院']
Teamfull['苏世民书院'] = ['苏世民书院', '苏世民书院']
Teamfull['化工'] = ['化学工程系', '化学工程系']
Teamfull['化工系'] = ['化学工程系', '化学工程系']
Teamfull['化学工程系'] = ['化学工程系', '化学工程系']
Teamfull['精仪'] = ['精密仪器系', '精密仪器系']
Teamfull['精仪系'] = ['精密仪器系', '精密仪器系']
Teamfull['精密仪器系'] = ['精密仪器系', '精密仪器系']
Teamfull['计算机'] = ['计算机系', '计算机科学与技术系']
Teamfull['计算机系'] = ['计算机系', '计算机科学与技术系']
Teamfull['计算机科学与技术系'] = ['计算机系', '计算机科学与技术系']
Teamfull['汽车'] = ['汽车工程系', '汽车工程系']
Teamfull['汽车系'] = ['汽车工程系', '汽车工程系']
Teamfull['汽车工程系'] = ['汽车工程系', '汽车工程系']
Teamfull['自动化'] = ['自动化系', '自动化系']
Teamfull['自动化系'] = ['自动化系', '自动化系']
Teamfull['材料'] = ['材料学院', '材料学院']
Teamfull['材料学院'] = ['材料学院', '材料学院']
def getabbr(teamname):
    return Teamabbrs[teamname][0]
def getfull(teamabbr,full=False):
    if full:
        if teamabbr in Teamfull.keys():
            return Teamfull[teamabbr][1]
        else:
            return "NOT FOUND"
    else:
        if teamabbr in Teamfull.keys():
            return Teamfull[teamabbr][0]
        else:
            return "NOT FOUND"
#fp = open('TeamDict.php','w')
#fp.write('<?php\n$dict = array(\n')
#for key,value in Teamfull.items():
#    fp.write('\"' + str(key) + '\" => '+'\"'+str(value[0])+'\",\n')
#fp.write(');\n$dict2 = array(\n')
#for key,value in Teamfull.items():
#    fp.write('\"' + str(key) + '\" => '+'\"'+str(value[1])+'\",\n')
#fp.write(');\n?>')
#fp.close()
